# General Jekyll Config
url: http://blog.bltavares.com
permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, _posts/*.org]
timezone: America/Sao_Paulo
redcarpet:
    extensions:
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks

# Theme customization - please change from the defaults!
data:
  # Color for top bar, links, etc
  background_color: '#fffffa'
  highlight_color: '#444'
  code_background: '#fafaf0'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: bltavares
    twitter: bltavares

  name: Bruno Tavares
  email: contato@bltavares.com
  tagline: "blog"

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true

## GitHub Defaults that we can change
kramdown:
  input: GFM
  hard_wrap: false

## GitHub Defaults that we cannot change
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
