# General Jekyll Config
url: http://blog.bltavares.com
permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, _posts/*.org]
timezone: America/Sao_Paulo
redcarpet:
    extensions:
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks

gems:
    - jekyll-sitemap

## GitHub Defaults that we can change
kramdown:
  input: GFM
  hard_wrap: false

## GitHub Defaults that we cannot change
lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
