# General Jekyll Config
url: https://blog.bltavares.com
permalink: pretty
exclude: [LICENSE, CNAME, README.md, .gitignore, _posts/*.org, vendor, Gemfile, Gemfile.lock]
include: [".well-known", "dat.json"]
keep_files: [".datignore", ".dat", "dat.json"]
timezone: America/Sao_Paulo
redcarpet:
    extensions:
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

## SEO Tag plugin
title: Bruno Lara Tavares - Blog
description: "A tech blog full of opinions"
author:
  name: Bruno Lara Tavares
  twitter: bltavares

twitter:
  username: bltavares

facebook:
  publisher: bltavares

social:
  name: Bruno Lara Tavares
  links:
    - https://twitter.com/bltavares
    - https://github.com/bltavares
    - https://www.linkedin.com/in/bltavares

webmaster_verifications:
  yandex: c256e221e48f6bd4
  bing: 0411A18071388E4453DC05E26EBB943F

## GitHub Defaults that we can change
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

## GitHub Defaults that we cannot change
lsi: false
incremental: false
highlighter: rouge
gist:
  noscript: false
