# General Jekyll Config
pygments: true
url: http://blog.bltavares.com
permalink: pretty
lsi: true
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: redcarpet
redcarpet:
    extensions:
      - hard_wrap
      - no_intra_emphasis
      - autolink
      - strikethrough
      - fenced_code_blocks

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#859900'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: bltavares
    twitter: bltavares

  # "Hi, I'm _______"
  name: Bruno Tavares
  email: contato@bltavares.com
  tagline: "blog"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
