version: '3'

services:
  jekyll:
    image: jekyll/jekyll:3.8.5
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve --watch --drafts --force_polling --incremental
  # zola:
  #   image: ghcr.io/getzola/zola:v0.17.2
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   ports:
  #     - 8080:8080
  #     - 1024:1024
  #   user: 1000:1000
  #   command: "serve --interface 0.0.0.0 --port 8080 --base-url localhost"
