#+OPTIONS: toc:nil
#+begin_html
---
layout: post
title: How tty.space came to be and how I see it
tags:
- tty.space
- community
---
#+end_html
* How tty.space came to be
  
A while ago, [[http://tilde.club/~ford/][Paul Ford]] created tilde.club, [[https://medium.com/message/tilde-club-i-had-a-couple-drinks-and-woke-up-with-1-000-nerds-a8904f0a2ebf][while he was drunk]]. And a
bunch of people liked the idea and joined it.

It had streak me as a very interesting project at the time, but as
things happen when they hit Hacker News, it was all crazy hyped. There
was no way to get an account, and I didn't want to dedicate time for
trying to be part of that.

But the other day, I was browsing and reading some about the new TLDs
when one pair of TLDs got my attention. tilde.club has a really cool
new .club TLD, and there was a .space TLD as well. The price was
affordable and there was a bunch of namehacking available on this
fresh new TLD spaces (pun intended).

I got really excited. "I could run my own tilde.club!". After all, it
is just a server with a HTTP server and users willing to play with it.
I asked a bunch of friends around some cool domain names, and settled
on [[http://tty.space/][tty.space]]. Short, geeky and cool domain hack.

* How do I see tty.space

[[http://tty.space][tty.space]] is just one more web server on the cloud. But I see
potential on it.

It is kinda of a nostalgia from a time I didn't participate. I keep
reading about how the internet was made of small distributed
connections, sharing news all over the world over between small groups
of conencted nodes, not assuming that the network is reliable and I
want to see how that was.

It sounds like a vibrant community, getting together on a shared
resource and sharing knowledge. A resource that feels just enough
handcrafted compared to the cloud. It could be rebuilt, but it will be
not the same.

I've learned so much about NNTP, email, wall, processes from other
users, and permissions. Tiny bash scripts generating HTML pages. And
there is no rush feeling of needing to be web scale or real time. No
feelings of shame on the management scripts. No fear of crashing
production.

And it is OK. This is a space to mess with things, to hack it open and
learn with the crashes. I see the potential to build a little small
hacker community amidst so many other production line communities.

Happy Hacking.
